// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyb3PdKq05E8LUHJ-I5XZqZOt-tXe99HM',
    appId: '1:879775374617:web:d4e1838b6e497b7037f988',
    messagingSenderId: '879775374617',
    projectId: 'bhuwana-guard',
    authDomain: 'bhuwana-guard.firebaseapp.com',
    storageBucket: 'bhuwana-guard.firebasestorage.app',
    measurementId: 'G-9Q5FHN6ZNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4YwNusnqogvkTpsarjQu0u9oCS1bQcKw',
    appId: '1:879775374617:android:289a0efe0536c08537f988',
    messagingSenderId: '879775374617',
    projectId: 'bhuwana-guard',
    storageBucket: 'bhuwana-guard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsr3R1xkr1-TWNWowGumKlslvmbn1E1qk',
    appId: '1:879775374617:ios:d5dbeb61c1efb09b37f988',
    messagingSenderId: '879775374617',
    projectId: 'bhuwana-guard',
    storageBucket: 'bhuwana-guard.firebasestorage.app',
    iosBundleId: 'com.example.bhuwanaGuardMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsr3R1xkr1-TWNWowGumKlslvmbn1E1qk',
    appId: '1:879775374617:ios:d5dbeb61c1efb09b37f988',
    messagingSenderId: '879775374617',
    projectId: 'bhuwana-guard',
    storageBucket: 'bhuwana-guard.firebasestorage.app',
    iosBundleId: 'com.example.bhuwanaGuardMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyb3PdKq05E8LUHJ-I5XZqZOt-tXe99HM',
    appId: '1:879775374617:web:f981a4ae192d34a037f988',
    messagingSenderId: '879775374617',
    projectId: 'bhuwana-guard',
    authDomain: 'bhuwana-guard.firebaseapp.com',
    storageBucket: 'bhuwana-guard.firebasestorage.app',
    measurementId: 'G-DLPGG6FBMY',
  );
}
